# Generated by Django 3.2.13 on 2022-05-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxygroup',
            options={'verbose_name': 'Граппа', 'verbose_name_plural': 'Группы'},
        ),
    ]
