# Generated by Django 3.2.13 on 2022-05-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(max_length=500, verbose_name='ФИО научного руководителя')),
                ('students_full_name', models.CharField(max_length=500, verbose_name='ФИО обучающегося')),
                ('review', models.FileField(upload_to='', verbose_name='Файл отзыва')),
                ('graduation_work', models.FileField(upload_to='', verbose_name='Файл ВКР')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления')),
                ('level_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.leveleducation', verbose_name='Уровни образования')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.qualification', verbose_name='Квалификация образования')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Пакет документов',
                'verbose_name_plural': 'Пакеты документов',
            },
        ),
    ]
